name: Code Checks

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Init environment
        uses: ./.github/actions/init-environment
      - name: Run formatter
        run: black --check .
  type-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Init environment
        uses: ./.github/actions/init-environment
      - name: Run type checker
        uses: jakebailey/pyright-action@v1
