name: Publish

on:
  release:
    types: [published]

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Init environment
        uses: ./.github/actions/init-environment
      - name: Poetry Config
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Poetry Build
        run: poetry build
      - name: Poetry Publish
        run: poetry publish
