name: Release Backport
on:
  push:
    branches:
      - releases/*
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release
        uses: googleapis/release-please-action@v3
        with:
          release-type: python
          versioning-strategy: always-bump-patch
          default-branch: ${{ github.ref_name }} 
