name: Release Main
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          versioning-strategy: always-bump-minor
          target-branch: ${{ github.ref_name }}
