name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    services:
      postgres:
        image: ankane/pgvector:v0.5.0
        env:
            POSTGRES_USER: ${{ secrets.UNIT_POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.UNIT_POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.UNIT_POSTGRES_DB }}
        ports:
            - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Init environment 
        uses: ./.github/actions/init-environment 
      - name: Run unit tests
        run: pytest -n auto tests/unit
